/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Office.glb 
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function OfficeRoom(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/public/models-room/Office.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (materials) {
      // Màu xám cho tường
      if (materials["palette.002"]) {
        materials["palette.002"].color.set("#808080"); // Màu xám
      }

      // Màu trắng viền đen cho đồng hồ
      if (materials["palette.001"]) {
        materials["palette.001"].color.set("#FFFFFF"); // Màu trắng
      }
      if (materials["Monitors.001"]) {
        materials["Monitors.001"].color.set("#000000"); // Màu đen cho viền
      }
      if (materials["palette.003"]) {
        materials["palette.003"].color.set("#941646"); // Màu do
      }
    }
  }, [materials]);
  useEffect(() => {
    actions["Armature|mixamo.com|Layer0"].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="transform4" />
        <group name="transform10" />
        <group name="transform14" />
        <group name="transform11" />
        <group name="transform16" />
        <group name="transform1" />
        <group name="transform13" />
        <group name="transform2" />
        <group name="transform6" />
        <group name="transform5" />
        <group name="transform3" />
        <group name="transform8" />
        <group name="transform7" />
        <group name="transform9" />
        <group name="transform12" />
        <group name="transform15" />
        <group name="transform20" />
        <group name="transform18" />
        <group name="transform22" />
        <group name="transform24" />
        <group name="transform21" />
        <group name="transform19" />
        <group name="transform23" />
        <group name="transform25" />
        <group name="transform17" />
        <group
          name="pCube1"
          position={[1.219, 2.139, 1.249]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.337, 0.135, 0.345]}
        >
          <group
            name="transform4001"
            position={[-1.359, -12.444, 6.201]}
            rotation={[-1.702, -0.579, 0.291]}
            scale={[4.43, 2.899, 6.615]}
          />
        </group>
        <group
          name="pCube2"
          position={[1.368, 2.13, 1.166]}
          rotation={[1.648, 0.138, -0.513]}
          scale={[0.081, 0.095, 0.092]}
        >
          <group
            name="transform10001"
            position={[-11.795, -17.799, 21.858]}
            rotation={[-1.634, -0.487, -0.24]}
            scale={[11.924, 10.942, 11.005]}
          />
        </group>
        <group
          name="pCube3"
          position={[1.353, 2.188, 1.218]}
          rotation={[1.651, 0.394, -0.192]}
          scale={[0.132, 0.094, 0.186]}
        >
          <group
            name="transform14001"
            position={[-14.355, -15.221, 8.537]}
            rotation={[-1.707, -0.28, -0.497]}
            scale={[7.438, 5.784, 10.594]}
          />
        </group>
        <group
          name="pCube4"
          position={[1.399, 2.164, 1.296]}
          rotation={[1.261, 0.168, -0.481]}
          scale={[0.047, 0.223, 0.183]}
        >
          <group
            name="transform11001"
            position={[-12.657, -10.991, 7.704]}
            rotation={[-1.073, -0.633, -0.295]}
            scale={[18.809, 5.362, 11.146]}
          />
        </group>
        <group
          name="pCube5"
          position={[1.396, 2.065, 1.225]}
          rotation={[Math.PI / 2, 0, -0.354]}
          scale={[0.023, 0.142, 0.121]}
        >
          <group
            name="transform16001"
            position={[-37.888, -11.52, 17.053]}
            rotation={[-1.359, -0.596, -0.426]}
            scale={[40.253, 8.26, 16.272]}
          />
        </group>
        <group
          name="pCube6"
          position={[1.219, 1.686, 1.249]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.708, 0.524, 0.54]}
        >
          <group
            name="transform1001"
            position={[-0.646, -3.214, 3.121]}
            rotation={[-1.61, -0.517, 0.108]}
            scale={[1.543, 1.851, 1.803]}
          />
        </group>
        <group
          name="pCube7"
          position={[1.351, 2.24, 1.236]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.007, 0.084, 0.035]}
        >
          <group
            name="transform13001"
            position={[-87.779, -20.713, 63.609]}
            rotation={[-1.204, -0.703, -0.45]}
            scale={[132.361, 28.393, 74.299]}
          />
        </group>
        <group
          name="Plane005"
          position={[1.545, 1.555, 1.313]}
          rotation={[0.979, 0.361, -1.566]}
          scale={[0.036, 0.013, 0.008]}
        >
          <group
            name="transform2001"
            position={[53.799, -130.285, -3.073]}
            rotation={[-0.354, -0.84, 0.704]}
            scale={[87.229, 106.055, 74.059]}
          />
        </group>
        <group
          name="Plane006"
          position={[1.219, -0.012, 1.249]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.163, 0.132, 0.145]}
        >
          <group
            name="transform6001"
            position={[-2.809, -12.72, -0.082]}
            rotation={[-1.597, -0.512, 0.075]}
            scale={[6.497, 6.898, 7.242]}
          />
        </group>
        <group
          name="pCube8"
          position={[1.381, 0.899, 1.305]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.163, 0.132, 0.145]}
        >
          <group
            name="transform5001"
            position={[-3.508, -13.682, 6.199]}
            rotation={[-1.597, -0.512, 0.075]}
            scale={[6.497, 6.898, 7.242]}
          />
        </group>
        <group
          name="pCube9"
          position={[1.273, 2.274, 1.44]}
          rotation={[1.18, 0.209, -0.466]}
          scale={[0.01, 0.029, 0.007]}
        >
          <group
            name="transform3001"
            position={[-41.272, -92.473, 178.826]}
            rotation={[-0.974, -0.582, -0.196]}
            scale={[93.505, 129.609, 77.01]}
          />
        </group>
        <group
          name="pCube10"
          position={[1.219, -0.011, 1.249]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.163, 0.132, 0.145]}
        >
          <group
            name="transform8001"
            position={[-2.809, -12.72, -0.075]}
            rotation={[-1.597, -0.512, 0.075]}
            scale={[6.497, 6.898, 7.242]}
          />
        </group>
        <group
          name="Plane007"
          position={[1.219, -0.012, 1.249]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.163, 0.132, 0.145]}
        >
          <group
            name="transform7001"
            position={[-2.809, -12.72, -0.082]}
            rotation={[-1.597, -0.512, 0.075]}
            scale={[6.497, 6.898, 7.242]}
          />
        </group>
        <group
          name="pCube11"
          position={[1.219, -0.012, 1.249]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.163, 0.132, 0.145]}
        >
          <group
            name="transform9001"
            position={[-2.809, -12.72, -0.082]}
            rotation={[-1.597, -0.512, 0.075]}
            scale={[6.497, 6.898, 7.242]}
          />
        </group>
        <group
          name="pCube12"
          position={[1.219, -0.012, 1.249]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.163, 0.132, 0.145]}
        >
          <group
            name="transform12001"
            position={[-2.809, -12.72, -0.082]}
            rotation={[-1.597, -0.512, 0.075]}
            scale={[6.497, 6.898, 7.242]}
          />
        </group>
        <group
          name="pCube13"
          position={[1.219, -0.012, 1.249]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.163, 0.132, 0.145]}
        >
          <group
            name="transform15001"
            position={[-2.809, -12.72, -0.082]}
            rotation={[-1.597, -0.512, 0.075]}
            scale={[6.497, 6.898, 7.242]}
          />
        </group>
        <group
          name="pCube14"
          position={[1.219, -0.012, 1.249]}
          rotation={[Math.PI / 2, 0, -0.508]}
          scale={[0.163, 0.132, 0.145]}
        >
          <group name="polySurface1">
            <group
              name="transform20001"
              position={[-2.809, -12.72, -0.082]}
              rotation={[-1.597, -0.512, 0.075]}
              scale={[6.497, 6.898, 7.242]}
            />
          </group>
          <group name="polySurface2">
            <group
              name="transform18001"
              position={[-2.809, -12.72, -0.082]}
              rotation={[-1.597, -0.512, 0.075]}
              scale={[6.497, 6.898, 7.242]}
            />
          </group>
          <group name="polySurface3">
            <group
              name="transform22001"
              position={[-2.809, -12.72, -0.082]}
              rotation={[-1.597, -0.512, 0.075]}
              scale={[6.497, 6.898, 7.242]}
            />
          </group>
          <group name="polySurface4">
            <group
              name="transform24001"
              position={[-2.809, -12.72, -0.082]}
              rotation={[-1.597, -0.512, 0.075]}
              scale={[6.497, 6.898, 7.242]}
            />
          </group>
          <group name="polySurface5">
            <group
              name="transform21001"
              position={[-2.809, -12.72, -0.082]}
              rotation={[-1.597, -0.512, 0.075]}
              scale={[6.497, 6.898, 7.242]}
            />
          </group>
          <group name="polySurface6">
            <group
              name="transform19001"
              position={[-2.809, -12.72, -0.082]}
              rotation={[-1.597, -0.512, 0.075]}
              scale={[6.497, 6.898, 7.242]}
            />
          </group>
          <group name="polySurface7">
            <group
              name="transform23001"
              position={[-2.809, -12.72, -0.082]}
              rotation={[-1.597, -0.512, 0.075]}
              scale={[6.497, 6.898, 7.242]}
            />
          </group>
          <group name="polySurface8">
            <group
              name="transform25001"
              position={[-2.809, -12.72, -0.082]}
              rotation={[-1.597, -0.512, 0.075]}
              scale={[6.497, 6.898, 7.242]}
            />
          </group>
          <group
            name="transform17001"
            position={[-2.809, -12.72, -0.082]}
            rotation={[-1.597, -0.512, 0.075]}
            scale={[6.497, 6.898, 7.242]}
          />
        </group>
        <group
          name="Armature"
          position={[0.75, 0, 1]}
          rotation={[Math.PI / 2, 0, -1]}
          scale={[0.165, 0.165, 0.165]}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="polySurface51"
            geometry={nodes.polySurface51.geometry}
            material={materials["lambert2.001"]}
            skeleton={nodes.polySurface51.skeleton}
          />
          <skinnedMesh
            name="polySurface61"
            geometry={nodes.polySurface61.geometry}
            material={materials["lambert3.001"]}
            skeleton={nodes.polySurface61.skeleton}
          />
          <skinnedMesh
            name="polySurface71"
            geometry={nodes.polySurface71.geometry}
            material={materials["blinn1.001"]}
            skeleton={nodes.polySurface71.skeleton}
          />
          <skinnedMesh
            name="polySurface81"
            geometry={nodes.polySurface81.geometry}
            material={materials["lambert2.001"]}
            skeleton={nodes.polySurface81.skeleton}
          />
        </group>
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials["palette.001"]}
          position={[-0.21, 0.173, 0.635]}
          rotation={[0, -0.664, 0]}
        />
        <mesh
          name="Cylinder001"
          geometry={nodes.Cylinder001.geometry}
          material={materials["palette.001"]}
          position={[-0.21, 0.318, 0.635]}
          rotation={[0, -0.664, 0]}
        />
        <mesh
          name="Cylinder007"
          geometry={nodes.Cylinder007.geometry}
          material={materials["palette.001"]}
          position={[-0.21, 0.562, 0.635]}
          rotation={[0, -0.678, 0]}
        />
        <mesh
          name="Cylinder008"
          geometry={nodes.Cylinder008.geometry}
          material={materials["palette.001"]}
          position={[-0.26, 0.463, 0.699]}
          rotation={[-0.738, -0.525, -0.427]}
        />
        <mesh
          name="Plane002"
          geometry={nodes.Plane002.geometry}
          material={materials["palette.001"]}
          position={[1.733, 0.425, -1.067]}
          rotation={[0, -1.493, 0]}
        />
        <mesh
          name="Plane003"
          geometry={nodes.Plane003.geometry}
          material={materials["palette.001"]}
          position={[1.733, 0.693, -0.712]}
          rotation={[0, -0.028, 0]}
        />
        <mesh
          name="Plane004"
          geometry={nodes.Plane004.geometry}
          material={materials["palette.001"]}
          position={[1.733, 0.426, -0.768]}
          rotation={[0, 1.552, 0]}
        />
        <mesh
          name="Cube055"
          geometry={nodes.Cube055.geometry}
          material={materials["palette.001"]}
          position={[1.771, 0.141, -0.934]}
          rotation={[0, -0.318, 0]}
        />
        <mesh
          name="Cube034"
          geometry={nodes.Cube034.geometry}
          material={materials["palette.001"]}
          position={[1.739, 0.105, -0.868]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          name="Cube035"
          geometry={nodes.Cube035.geometry}
          material={materials["palette.001"]}
          position={[1.739, 0.105, -0.443]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          name="Cube036"
          geometry={nodes.Cube036.geometry}
          material={materials["palette.001"]}
          position={[1.739, 0.095, -0.455]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          name="Cube037"
          geometry={nodes.Cube037.geometry}
          material={materials["palette.001"]}
          position={[1.613, 0.033, -0.536]}
          rotation={[0, -1.571, 0]}
        />
        <mesh
          name="Cylinder031"
          geometry={nodes.Cylinder031.geometry}
          material={materials["palette.001"]}
          position={[1.664, 0.702, -1.089]}
          scale={1.451}
        />
        <mesh
          name="Cube031"
          geometry={nodes.Cube031.geometry}
          material={materials["palette.001"]}
          position={[-0.974, 2.546, -1.441]}
        />
        <mesh
          name="Cube033"
          geometry={nodes.Cube033.geometry}
          material={materials["palette.001"]}
          position={[-0.214, 2.667, -1.441]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["palette.001"]}
          position={[-0.204, 1.397, -1.439]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cube024"
          geometry={nodes.Cube024.geometry}
          material={materials["palette.001"]}
          position={[-0.539, 0.199, -0.466]}
        />
        <mesh
          name="Cube023"
          geometry={nodes.Cube023.geometry}
          material={materials["palette.001"]}
          position={[0.161, 0.048, -0.172]}
        />
        <mesh
          name="Cube025"
          geometry={nodes.Cube025.geometry}
          material={materials["palette.001"]}
          position={[-0.539, 0.667, -0.471]}
        />
        <mesh
          name="Cube026"
          geometry={nodes.Cube026.geometry}
          material={materials["palette.001"]}
          position={[0.262, 0.73, -0.471]}
        />
        <mesh
          name="Cube027"
          geometry={nodes.Cube027.geometry}
          material={materials["palette.001"]}
          position={[-0.375, 0.73, -0.471]}
        />
        <mesh
          name="Cube028"
          geometry={nodes.Cube028.geometry}
          material={materials["palette.001"]}
          position={[-1.302, 0.921, -0.471]}
          rotation={[0, 0, -0.642]}
        />
        <mesh
          name="Cube029"
          geometry={nodes.Cube029.geometry}
          material={materials["palette.001"]}
          position={[-1.379, 0.937, -0.471]}
          rotation={[0, 0, -2.201]}
        />
        <mesh
          name="Cube030"
          geometry={nodes.Cube030.geometry}
          material={materials["palette.001"]}
          position={[-1.494, 0.806, -0.471]}
          rotation={[0, 0, -0.642]}
        />
        <mesh
          name="Cylinder026"
          geometry={nodes.Cylinder026.geometry}
          material={materials["palette.001"]}
          position={[-1.286, 0.114, 0.156]}
          rotation={[0, -0.994, 0]}
        />
        <mesh
          name="Circle"
          geometry={nodes.Circle.geometry}
          material={materials["palette.001"]}
          position={[-1.286, 1.838, 0.156]}
          rotation={[0, 1.376, 0]}
        />
        <mesh
          name="Circle001"
          geometry={nodes.Circle001.geometry}
          material={materials["palette.001"]}
          position={[-1.286, 1.425, 0.156]}
          rotation={[0, 0.076, 0]}
        />
        <mesh
          name="Cube052"
          geometry={nodes.Cube052.geometry}
          material={materials["palette.001"]}
          position={[-1.073, 1.285, 0.224]}
          rotation={[0, 1.255, 0]}
        />
        <mesh
          name="Cylinder027"
          geometry={nodes.Cylinder027.geometry}
          material={materials["palette.001"]}
          position={[-1.158, 1.817, -0.028]}
          rotation={[0, 0.985, 0]}
        />
        <mesh
          name="Vert"
          geometry={nodes.Vert.geometry}
          material={materials["palette.001"]}
          position={[-1.073, 1.122, 0.224]}
        />
        <mesh
          name="Cube019"
          geometry={nodes.Cube019.geometry}
          material={materials["palette.001"]}
          position={[-1.812, 2.113, -0.47]}
        />
        <group
          name="Cube021"
          position={[-1.225, 2.329, -0.471]}
          rotation={[0, 0, -0.574]}
        >
          <mesh
            name="Cube052_1"
            geometry={nodes.Cube052_1.geometry}
            material={materials["palette.001"]}
          />
          <mesh
            name="Cube052_2"
            geometry={nodes.Cube052_2.geometry}
            material={materials["Monitors.001"]}
          />
        </group>
        <mesh
          name="Cube022"
          geometry={nodes.Cube022.geometry}
          material={materials["palette.001"]}
          position={[-1.251, 2.346, -0.471]}
          rotation={[0, 0, -0.574]}
        />
        <mesh
          name="Cube006"
          geometry={nodes.Cube006.geometry}
          material={materials["palette.001"]}
          position={[-1.306, 0.147, 0.786]}
        />
        <mesh
          name="Cube007"
          geometry={nodes.Cube007.geometry}
          material={materials["palette.001"]}
          position={[-1.306, 0.391, 0.786]}
        />
        <mesh
          name="Cylinder010"
          geometry={nodes.Cylinder010.geometry}
          material={materials["palette.001"]}
          position={[-1.306, 0.713, 0.786]}
        />
        <mesh
          name="Cube008"
          geometry={nodes.Cube008.geometry}
          material={materials["palette.001"]}
          position={[-1.306, 0.845, 0.786]}
        />
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={materials["palette.001"]}
          position={[-1.167, 0.845, 0.786]}
        />
        <mesh
          name="Cylinder012"
          geometry={nodes.Cylinder012.geometry}
          material={materials["palette.001"]}
          position={[-1.382, 1.03, 0.786]}
          rotation={[0, 0.889, 0]}
        />
        <mesh
          name="Cylinder015"
          geometry={nodes.Cylinder015.geometry}
          material={materials["palette.001"]}
          position={[-1.615, 1.234, 1.073]}
          rotation={[0, 1.037, Math.PI]}
        />
        <mesh
          name="Cylinder013"
          geometry={nodes.Cylinder013.geometry}
          material={materials["palette.001"]}
          position={[-1.615, 1.236, 1.073]}
          rotation={[0, 0.889, 0]}
        />
        <group name="App_Monitor" position={[-1.37, 1.454, 0.786]}>
          <mesh
            name="Cube062"
            geometry={nodes.Cube062.geometry}
            material={materials["palette.001"]}
          />
          <mesh
            name="Cube062_1"
            geometry={nodes.Cube062_1.geometry}
            material={materials["Monitors.001"]}
          />
        </group>
        <mesh
          name="Cylinder014"
          geometry={nodes.Cylinder014.geometry}
          material={materials["palette.001"]}
          position={[-1.297, 0.959, 0.963]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="Cylinder017"
          geometry={nodes.Cylinder017.geometry}
          material={materials["palette.001"]}
          position={[-1.232, 0.87, 0.969]}
        />
        <mesh
          name="Cylinder018"
          geometry={nodes.Cylinder018.geometry}
          material={materials["palette.001"]}
          position={[-1.161, 0.87, 0.89]}
        />
        <mesh
          name="Cylinder019"
          geometry={nodes.Cylinder019.geometry}
          material={materials["palette.001"]}
          position={[-1.149, 0.87, 0.787]}
        />
        <mesh
          name="Cube014"
          geometry={nodes.Cube014.geometry}
          material={materials["palette.001"]}
          position={[-1.214, 0.864, 0.786]}
        />
        <mesh
          name="Cube015"
          geometry={nodes.Cube015.geometry}
          material={materials["palette.001"]}
          position={[-1.202, 0.868, 0.886]}
        />
        <mesh
          name="Cube016"
          geometry={nodes.Cube016.geometry}
          material={materials["palette.001"]}
          position={[-1.307, 0.989, 0.963]}
          rotation={[0, 0, -1.44]}
        />
        <mesh
          name="Cube017"
          geometry={nodes.Cube017.geometry}
          material={materials["palette.001"]}
          position={[-1.118, 0.042, 1.043]}
        />
        <mesh
          name="Cube018"
          geometry={nodes.Cube018.geometry}
          material={materials["palette.001"]}
          position={[-1.048, 0.312, 0.963]}
        />
        <mesh
          name="Vert002"
          geometry={nodes.Vert002.geometry}
          material={materials["palette.001"]}
          position={[-1.563, 0.251, 0.611]}
        />
        <mesh
          name="Cylinder028"
          geometry={nodes.Cylinder028.geometry}
          material={materials["palette.001"]}
          position={[-1.781, 0.254, 1.485]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="Cylinder030"
          geometry={nodes.Cylinder030.geometry}
          material={materials["palette.001"]}
          position={[-1.405, 0.459, 1.073]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="frame"
          geometry={nodes.frame.geometry}
          material={materials["palette.001"]}
          position={[-1.763, 1.292, 1.509]}
        />
        <mesh
          name="shells"
          geometry={nodes.shells.geometry}
          material={materials["palette.001"]}
          position={[-1.767, 1.076, 1.509]}
        />
        <mesh
          name="bottle3"
          geometry={nodes.bottle3.geometry}
          material={materials["palette.001"]}
          position={[-1.763, 1.123, 1.41]}
        />
        <mesh
          name="bottle1"
          geometry={nodes.bottle1.geometry}
          material={materials["palette.001"]}
          position={[-1.74, 1.54, 1.585]}
        />
        <mesh
          name="tablets1"
          geometry={nodes.tablets1.geometry}
          material={materials["palette.001"]}
          position={[-1.745, 1.09, 1.574]}
          rotation={[0, -0.916, 0]}
        />
        <mesh
          name="bottle2"
          geometry={nodes.bottle2.geometry}
          material={materials["palette.001"]}
          position={[-1.765, 1.329, 1.466]}
        />
        <mesh
          name="glass"
          geometry={nodes.glass.geometry}
          material={materials["palette.001"]}
          position={[-1.765, 1.329, 1.584]}
        />
        <mesh
          name="tablets2"
          geometry={nodes.tablets2.geometry}
          material={materials["palette.001"]}
          position={[-1.761, 0.911, 1.423]}
          rotation={[0, 0.572, 0]}
        />
        <mesh
          name="tablets3"
          geometry={nodes.tablets3.geometry}
          material={materials["palette.001"]}
          position={[-1.761, 0.917, 1.423]}
          rotation={[-0.065, -0.298, -0.065]}
        />
        <mesh
          name="bottle4"
          geometry={nodes.bottle4.geometry}
          material={materials["palette.001"]}
          position={[-1.704, 0.933, 1.649]}
          rotation={[-1.558, -0.022, -1.047]}
        />
        <group
          name="clockBase"
          position={[-1.813, 2.224, 1.412]}
          rotation={[0, 0, -Math.PI / 2]}
        >
          <mesh
            name="Cylinder045"
            geometry={nodes.Cylinder045.geometry}
            material={materials["palette.001"]}
          />
          <mesh
            name="Cylinder045_1"
            geometry={nodes.Cylinder045_1.geometry}
            material={materials["Monitors.001"]}
          />
        </group>
        <mesh
          name="minuteHand"
          geometry={nodes.minuteHand.geometry}
          material={materials["palette.001"]}
          position={[-1.807, 2.224, 1.412]}
          rotation={[-0.718, 0, 0]}
        />
        <mesh
          name="hourHand"
          geometry={nodes.hourHand.geometry}
          material={materials["palette.001"]}
          position={[-1.81, 2.224, 1.412]}
          rotation={[3.017, 0, 0]}
        />
        <mesh
          name="clockmiddlescrew"
          geometry={nodes.clockmiddlescrew.geometry}
          material={materials["palette.001"]}
          position={[-1.806, 2.224, 1.412]}
        />
        <mesh
          name="walls"
          geometry={nodes.walls.geometry}
          material={materials["palette.002"]}
          position={[-2, 1, 0]}
        />
        <mesh
          name="floor"
          geometry={nodes.floor.geometry}
          material={materials["palette.001"]}
        />
        <mesh
          name="floorTile"
          geometry={nodes.floorTile.geometry}
          material={materials["palette.001"]}
          position={[0, -0.001, 0]}
        />
        <mesh
          name="lowerWall"
          geometry={nodes.lowerWall.geometry}
          material={materials["palette.001"]}
          position={[-0.001, 0.244, -1.937]}
        />
        <mesh
          name="socket"
          geometry={nodes.socket.geometry}
          material={materials["palette.003"]}
          position={[-1.777, 0.254, 1.485]}
        />
        <mesh
          name="socket2"
          geometry={nodes.socket2.geometry}
          material={materials["palette.003"]}
          position={[-1.777, 0.254, 1.651]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/public/models-room/Office.glb");
