/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 doctor.glb 
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function DoctorBreath(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/public/doctor.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.breathing.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="transform4" />
        <group name="transform10" />
        <group name="transform14" />
        <group name="transform11" />
        <group name="transform16" />
        <group name="transform1" />
        <group name="transform13" />
        <group name="transform2" />
        <group
          name="Plane006"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform6"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group name="transform5" />
        <group name="transform3" />
        <group
          name="pCube10"
          position={[-0.055, -0.096, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform8"
            position={[4.097, -0.934, -7.163]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="Plane007"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform7"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube11"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform9"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube12"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform12"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube13"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform15"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube14"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group name="polySurface1">
            <group
              name="transform20"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface2">
            <group
              name="transform18"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface3">
            <group
              name="transform22"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface4">
            <group
              name="transform24"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface5">
            <group
              name="transform21"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface6">
            <group
              name="transform19"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface7">
            <group
              name="transform23"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface8">
            <group
              name="transform25"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group
            name="transform17"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube1"
          position={[-0.055, 0.103, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.028, 0.014, 0.032]}
        >
          <group
            name="transform4001"
            position={[1.983, -0.913, 3.222]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[35.938, 31.215, 72.658]}
          />
        </group>
        <group
          name="pCube2"
          position={[-0.041, 0.102, 0.013]}
          rotation={[Math.PI / 2, 0.158, 0]}
          scale={[0.005, 0.01, 0.006]}
        >
          <group
            name="transform10001"
            position={[5.232, -1.307, 17.533]}
            rotation={[-1.56, 0.041, -0.163]}
            scale={[212.617, 164.457, 103.926]}
          />
        </group>
        <group
          name="pCube3"
          position={[-0.044, 0.108, 0.016]}
          rotation={[1.439, 0.381, 0.357]}
          scale={[0.002, 0.004, 0.005]}
        >
          <group
            name="transform14001"
            position={[-5.129, -7.462, 23.189]}
            rotation={[-1.787, 0.155, -0.755]}
            scale={[525.474, 297.671, 300.619]}
          />
        </group>
        <group
          name="pCube4"
          position={[-0.044, 0.106, 0.026]}
          rotation={[1.22, 0, 0]}
          scale={[0.004, 0.008, 0.007]}
        >
          <group
            name="transform11001"
            position={[11.403, -7.5, 12.492]}
            rotation={[-1.218, 0, 0]}
            scale={[258.767, 136.767, 126.03]}
          />
        </group>
        <group
          name="pCube5"
          position={[-0.041, 0.096, 0.019]}
          rotation={[Math.PI / 2, 0, 0.153]}
          scale={[0.001, 0.011, 0.011]}
        >
          <group
            name="transform16001"
            position={[25.386, -2.374, 8.567]}
            rotation={[-1.473, 0.425, 0.365]}
            scale={[660.654, 88.927, 137.985]}
          />
        </group>
        <group
          name="pCube6"
          position={[-0.055, 0.061, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.059, 0.053, 0.05]}
        >
          <group
            name="transform1001"
            position={[0.943, -0.236, 1.219]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[17.091, 19.924, 18.766]}
          />
        </group>
        <group
          name="pCube7"
          position={[-0.045, 0.113, 0.018]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.001, 0.009, 0.003]}
        >
          <group
            name="transform13001"
            position={[82.589, -2.102, 34.436]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1832.314, 305.695, 117.273]}
          />
        </group>
        <group
          name="Plane005"
          position={[-0.034, 0.049, 0.034]}
          rotation={[0.891, 0.055, -1.15]}
          scale={0}
        >
          <group
            name="transform2001"
            position={[234.661, 29.818, 117.2]}
            rotation={[-0.608, -0.704, 0.765]}
            scale={[4255.404, 5487.275, 4919.824]}
          />
        </group>
        <group
          name="Plane006001"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform6001"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube8"
          position={[-0.046, -0.012, 0.026]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform5001"
            position={[3.398, -1.895, -0.889]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube9"
          position={[-0.059, 0.116, 0.032]}
          rotation={[1.13, 0, 0]}
          scale={[0.001, 0.001, 0]}
        >
          <group
            name="transform3001"
            position={[71.338, -95.085, 411.336]}
            rotation={[-0.921, 0, 0]}
            scale={[1211.129, 4121.061, 2217.544]}
          />
        </group>
        <group
          name="pCube10001"
          position={[-0.055, -0.096, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform8001"
            position={[4.097, -0.934, -7.163]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="Plane007001"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform7001"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube11001"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform9001"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube12001"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform12001"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube13001"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group
            name="transform15001"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="pCube14001"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <group name="polySurface1001">
            <group
              name="transform20001"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface2001">
            <group
              name="transform18001"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface3001">
            <group
              name="transform22001"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface4001">
            <group
              name="transform24001"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface5001">
            <group
              name="transform21001"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface6001">
            <group
              name="transform19001"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface7001">
            <group
              name="transform23001"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group name="polySurface8001">
            <group
              name="transform25001"
              position={[4.097, -0.934, -7.17]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={74.273}
            />
          </group>
          <group
            name="transform17001"
            position={[4.097, -0.934, -7.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={74.273}
          />
        </group>
        <group
          name="Armature"
          position={[-0.055, -0.097, 0.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.013}
        >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="polySurface51"
            geometry={nodes.polySurface51.geometry}
            material={materials["lambert2.001"]}
            skeleton={nodes.polySurface51.skeleton}
          />
          <skinnedMesh
            name="polySurface61"
            geometry={nodes.polySurface61.geometry}
            material={materials["lambert3.001"]}
            skeleton={nodes.polySurface61.skeleton}
          />
          <skinnedMesh
            name="polySurface71"
            geometry={nodes.polySurface71.geometry}
            material={materials["blinn1.001"]}
            skeleton={nodes.polySurface71.skeleton}
          />
          <skinnedMesh
            name="polySurface81"
            geometry={nodes.polySurface81.geometry}
            material={materials["lambert2.001"]}
            skeleton={nodes.polySurface81.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/public/doctor.glb");
