/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WavingDoctor.glb 
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function WavingDoctor(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/public/WavingDoctor.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.waving.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="pCube1"
          position={[0, 0.148, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.021, 0.01, 0.024]}
        >
          <group
            name="transform4"
            position={[0, 0, 6.235]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[48.387, 42.028, 97.826]}
          />
        </group>
        <group
          name="pCube2"
          position={[0.01, 0.148, 0]}
          rotation={[Math.PI / 2, 0.158, 0]}
          scale={[0.003, 0.007, 0.005]}
        >
          <group
            name="transform10"
            position={[-9.653, 0, 31.663]}
            rotation={[-1.56, 0.041, -0.163]}
            scale={[286.265, 221.423, 139.926]}
          />
        </group>
        <group
          name="pCube3"
          position={[0.008, 0.152, 0.003]}
          rotation={[1.439, 0.381, 0.357]}
          scale={[0.001, 0.003, 0.004]}
        >
          <group
            name="transform14"
            position={[-53.516, 0.28, 37.441]}
            rotation={[-1.787, 0.155, -0.755]}
            scale={[707.494, 400.781, 404.75]}
          />
        </group>
        <group
          name="pCube4"
          position={[0.008, 0.15, 0.01]}
          rotation={[1.22, 0, 0]}
          scale={[0.003, 0.006, 0.005]}
        >
          <group
            name="transform11"
            position={[-2.871, -10.156, 25.633]}
            rotation={[-1.218, 0, 0]}
            scale={[348.402, 184.142, 169.686]}
          />
        </group>
        <group
          name="pCube5"
          position={[0.01, 0.143, 0.005]}
          rotation={[Math.PI / 2, 0, 0.153]}
          scale={[0.001, 0.008, 0.008]}
        >
          <group
            name="transform16"
            position={[-9.767, -0.415, 17.152]}
            rotation={[-1.473, 0.425, 0.365]}
            scale={[889.5, 119.731, 185.782]}
          />
        </group>
        <group
          name="pCube6"
          position={[0, 0.117, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.043, 0.04, 0.037]}
        >
          <group
            name="transform1"
            position={[0, 0, 3.143]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[23.011, 26.825, 25.266]}
          />
        </group>
        <group
          name="pCube7"
          position={[0.007, 0.155, 0.004]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0, 0.006, 0.002]}
        >
          <group
            name="transform13"
            position={[-18.489, -0.628, 63.948]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[2467.011, 411.585, 157.895]}
          />
        </group>
        <group
          name="Plane005"
          position={[0.016, 0.108, 0.016]}
          rotation={[0.891, 0.055, -1.15]}
          scale={0}
        >
          <group
            name="transform2"
            position={[313.178, -299.24, 626.388]}
            rotation={[-0.608, -0.704, 0.765]}
            scale={[5729.439, 7388.021, 6624.008]}
          />
        </group>
        <group name="Plane006" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            name="transform6"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
        <group
          name="pCube8"
          position={[0.007, 0.063, 0.01]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group
            name="transform5"
            position={[-0.7, -0.961, 6.281]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
        <group
          name="pCube9"
          position={[-0.003, 0.158, 0.015]}
          rotation={[1.13, 0, 0]}
          scale={[0.001, 0.001, 0]}
        >
          <group
            name="transform3"
            position={[4.527, -131.185, 830.293]}
            rotation={[-0.921, 0, 0]}
            scale={[1630.654, 5548.561, 2985.683]}
          />
        </group>
        <group name="pCube10" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            name="transform8"
            position={[0, 0, 0.007]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
        <group name="Plane007" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            name="transform7"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
        <group name="pCube11" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            name="transform9"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
        <group name="pCube12" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            name="transform12"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
        <group name="pCube13" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            name="transform15"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
        <group name="pCube14" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="polySurface1">
            <group
              name="transform20"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
          <group name="polySurface2">
            <group
              name="transform18"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
          <group name="polySurface3">
            <group
              name="transform22"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
          <group name="polySurface4">
            <group
              name="transform24"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
          <group name="polySurface5">
            <group
              name="transform21"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
          <group name="polySurface6">
            <group
              name="transform19"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
          <group name="polySurface7">
            <group
              name="transform23"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
          <group name="polySurface8">
            <group
              name="transform25"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
          <group
            name="transform17"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="polySurface51"
            geometry={nodes.polySurface51.geometry}
            material={materials.lambert2}
            skeleton={nodes.polySurface51.skeleton}
          />
          <skinnedMesh
            name="polySurface61"
            geometry={nodes.polySurface61.geometry}
            material={materials.lambert3}
            skeleton={nodes.polySurface61.skeleton}
          />
          <skinnedMesh
            name="polySurface71"
            geometry={nodes.polySurface71.geometry}
            material={materials.blinn1}
            skeleton={nodes.polySurface71.skeleton}
          />
          <skinnedMesh
            name="polySurface81"
            geometry={nodes.polySurface81.geometry}
            material={materials.lambert2}
            skeleton={nodes.polySurface81.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/public/WavingDoctor.glb");
