/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\zoom.glb 
*/

import { useGLTF } from "@react-three/drei";

export function Zoom(props) {
  const { nodes, materials } = useGLTF("/3d-zoom-app-logo/source/zoom.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 3, 6]} rotation={[Math.PI / 2, 0, 0]} scale={0.843}>
        <mesh
          geometry={nodes.Cylinder004.geometry}
          material={materials["glossy zoom"]}
        />
        <mesh
          geometry={nodes.Cylinder004_1.geometry}
          material={materials["GLOSSY YT.004"]}
        />
        <mesh
          geometry={nodes.Cylinder004_2.geometry}
          material={materials["glossy putih.016"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3d-zoom-app-logo/source/zoom.glb");
